# Generated by Django 6.0.1 on 2026-02-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=25)),
                ('body', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'about',
            },
        ),
    ]
