# Generated by Django 6.0.1 on 2026-02-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='body',
            new_name='about_description',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='heading',
            new_name='about_heading',
        ),
    ]
